### ISSUE TITLE
DataHandler Plugin - Stream

### ISSUE THREAD

**Issue by delemojo** [ThrDev/Socks5#11]
Is there a way to get a Stream from the DataHandler? Since its not working with `stream.Write(e.Buffer, e.Offset, e.Buffer.Length); stream.Flush();`

**Comment by ThrDev** [comment]
Unfortunately, there is not currently a way to get an underlying stream with a DataHandler plugin.
The convenient thing though is that you can create a stream in the plugin itself and the same instance will be stored for that particular connection until it closes. So technically, you can create an array of streams, pass one to the datahandler, then write to it every time there is data received or sent out.

**Comment by delemojo** [comment]
Do u have a Idea how to have the Server and the Client running in the same Application? For Example:
I have a Windows Form with WebBrowser and in this Form I also have the SOCKS5 Server running. Then Im using a Third Party Programm to redirect all packets from the webbrowser to the SOCKS5 Server so collect the data, but sadly I end up in a Infinite Loop. Do u have a idea how to fix this?
