### ISSUE TITLE
Socks5 block my whole application after 5-10 minutes

### ISSUE THREAD

**Issue by xavias31** [ThrDev/Socks5#14]
Hi,

i wrote a small application to set up a socks5 (with reverse over my vps) on my home pc so i can surf with it when im in the office.

But i have a problem, after a few minutes (like5-10min) my whole application freeze , without errors or exceptions. I can load a few sites with this socks but after this it just block my whole application and the bot is down. I tried without reverse, but same result.

im using socks5_minimal

**Comment by ThrDev** [comment]
Hey Xavias31,
Socks5_minimal is behind in terms of updates. For now I would recommend using the standard socks5 library for now until I get the minimal one up to date.
Let me know if the standard one causes those same issues for you.
On Aug 7, 2016 7:28 PM, xavias31 <notifications@github.com> wrote:Hi,

i wrote a small application to set up a socks5 (with reverse over my vps) on my home pc so i can surf with it when im in the office.

But i have a problem, after a few minutes (like5-10min) my whole application freeze , without errors or exceptions. I can load a few sites with this socks but after this it just block my whole application and the bot is down. I tried without reverse, but same result.

im using socks5_minimal

**Comment by xavias31** [comment]
I tested it with socks5. No freeze but i got all 30 seconds in Console this message:

"Error while connecting: TimedOut"

Any ideas ?

thx for your help !

**Comment by ThrDev** [comment]
Are you using the socks5 client or server?
