### ISSUE TITLE
Socks Client - Valid Ports Larger then Int16

### ISSUE THREAD

**Issue by zharris6** [ThrDev/Socks5#16]
Hello -

Running into an issue with a valid port ex: 35622 Cannot be converted to a 16 bit INT.

I tried to simply run Convert.ToInt32 and this breaks the application (data cannot be read and exception is thrown)

Any help would be appreciated! 

Class:  Socks.cs

```
        public byte[] GetData(bool NetworkToHostOrder) //NetworkToHostOrder = false
        {
            byte[] data;
            var port = 0;
            if(NetworkToHostOrder)
                port = IPAddress.NetworkToHostOrder(Port);
            else
                port = IPAddress.HostToNetworkOrder(Convert.ToInt16(Port));
```

**Comment by ThrDev** [comment]
Hey again!

You are indeed correct. I can't believe I missed this. I will push a fix tomorrow.

**Comment by ThrDev** [comment]
I've went ahead and synced a commit containing the fix. I just decided to go ahead and do it now. I've tested it and it should work properly. If not, please feel free to let me know!

**Comment by zharris6** [comment]
Hey ThrDev!

Thanks for your Quick response, It is much appreciated.

I am still getting an exception on line 263 of socks.cs

Convert.ToInt16(Port) the port is greater then a int16 value.

When i just change it to ToInt32, the app gets Hosed and doesn't connect or read data.

 ```
 line 263 of socks.cs

       public byte[] GetData(bool NetworkToHostOrder)
        {
            byte[] data;
            var port = 0;
            if(NetworkToHostOrder)
                port = IPAddress.NetworkToHostOrder(Port);
            else
                port = IPAddress.HostToNetworkOrder(Convert.ToInt16(Port));

```

**Comment by ThrDev** [comment]
Hey!

I'll push a fix as soon as I get home from work, no longer than about an hour and a half from now.

Thanks!

**Comment by ThrDev** [comment]
Hey there! I've pushed a fix. Please let me know if this patch works for you.

https://github.com/ThrDev/Socks5/commit/0717ade100ea8b17b34bdb302f6f652a78dbdadb

**Comment by zharris6** [comment]
No Luck bud. It compiles fine, but i am receiving this:

This could 100% be on my end though so don't go crazy. 

Have you tested it and it works? If so, it probably is on my side.

`Additional information: Method not found: 'socks5.Socks.SocksError socks5.Socks5Client.Socks.SendRequest(socks5.TCP.Client, socks5.Encryption.SocksEncryption, System.String, Int32)'.`

**Comment by ThrDev** [comment]
As far as I know, that method is now declared with a ushort instead of an int32 as the last parameter. As to why your code is compiling but throwing error at runtime....I'm not sure.

**Comment by zharris6** [comment]
Sorry To keep bothering you...

That Not Found exception was on my end, like i figured.

However, I am not receiving any reply from the SOCKS server now. Are you sure you tested this to be working on your side?

**Comment by zharris6** [comment]
I fixed it. I took the old revision and changed the below (nothing else).

Not sure if this will satisfy all of your requirements, but i can now connect to a target with a port range higher then Int16.

If that works for you, and your last commit doesn't.. maybe you should consider a revert?

line 263 of socks.cs

        ```
  port = IPAddress.HostToNetworkOrder(Convert.ToInt16(Port));
       to

                port = IPAddress.HostToNetworkOrder((short)Port);

```

**Comment by ThrDev** [comment]
I'm pretty sure I had changed all of the ports from 32-bit signed integers to 16-bit unsigned shorts.

https://github.com/ThrDev/Socks5/commit/0717ade100ea8b17b34bdb302f6f652a78dbdadb#diff-84ab0cbefff54786a59bff5b22b5bc9eR263

My last commit changed that. Is that the one you had used?

**Comment by zharris6** [comment]
Yes, That fixed the exception, however, with that change, i could not receive any data from my target.

I am not sure why.

I changed Convert.ToInt16 to (short) and everything worked and data started flowing

**Comment by ThrDev** [comment]
Okay, I will have to revert my commit. I appreciate all of your help. I'm still surprised that I missed this!

**Comment by zharris6** [comment]
Your welcome. 

I mean you could test it as is, but i'm pretty sure it isn't functional ATM.

**Comment by ThrDev** [comment]
If I make a new commit within the next 5 minutes or so, would you be able to test it for me? I would revert but I had a new project file added.

**Comment by zharris6** [comment]
ya sure. 

just to clear something up, As it sits now, no ports (Even ones that are int16) are working

**Comment by ThrDev** [comment]
Monodevelop messed up my formatting but this will have to do for now.

https://github.com/ThrDev/Socks5/commit/adbd72ff3419e9a54ac6c8dd948d51aa287e3756

**Comment by zharris6** [comment]
Nope, Same issue bud.

**Comment by zharris6** [comment]
You tried and can get a reply fine?

**Comment by ThrDev** [comment]
I'm so sorry for the delay.

After some investigation, it would make sense that you would have to cast it to a short, as HostToNetworkOrder basically reverses the endianness. Because of this, it effectively turns an unsigned 16-bit integer into a negative number. Because of this, it would have to be short because of the ability to go -32768 and 32768.

This has been thoroughly tested and fixed :) I'm sorry for all the confusion. I had been testing the Socks5Server thinking that was the problem, but I had forgotten you were utilizing the Socks5Client.

https://github.com/ThrDev/Socks5/commit/8f8248f403352df82264210ddd83accc652b65c8#diff-84ab0cbefff54786a59bff5b22b5bc9eR263

**Comment by zharris6** [comment]
Now we are cookin! Works great.

One last thing i changed in Socks5Client.cs below. I was getting null exceptions in my code.

Other then that, perfect!

        public bool Connected
        {
            get {

              return (Client == null) ?  false :  Client.Sock.Connected;

            }
        }

**Comment by ThrDev** [comment]
Awesome! Glad to hear! That last change was pushed and should be good now.
