### ISSUE TITLE
"System.ObjectDisposedException" in System.dll

### ISSUE THREAD

**Issue by TheBinaryLoop** [ThrDev/Socks5#19]
System.ObjectDisposedException: Auf das verworfene Objekt kann nicht zugegriffen werden.
Objektname: "System.Net.Sockets.Socket".
   bei System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult, SocketError& errorCode)
   bei Socks5.TCP.Client.DataReceived(IAsyncResult res) in F:\Programing\Visual C#\Socks5\Socks5\TCP\Client.cs:Zeile 37.
`int received = ((Socket)res.AsyncState).EndReceive(res, out err);`

**Comment by ThrDev** [comment]
This error should be handled by the try catch located here:
https://github.com/ThrDev/Socks5/blob/master/socks5/socks5/TCP/Client.cs#L52

Could you possibly explain what is happening/what you are doing when you are encountering this?

**Comment by TheBinaryLoop** [comment]
I just ran the the Demo and this error happend.

**Comment by ThrDev** [comment]
If you have CLR exceptions enabled, you will encounter this as an error. If you don't have that enabled, the error is handled for you. Please refer to:
https://github.com/ThrDev/Socks5/blob/master/socks5/socks5/TCP/Client.cs#L68

If I am missing something, please let me know.

**Comment by TheBinaryLoop** [comment]
How can i turn off CLR exceptions?

**Comment by ThrDev** [comment]
https://msdn.microsoft.com/en-us/library/d14azbfh(v=vs.110).aspx
