### ISSUE TITLE
Can I use the SocksClient to get a Socket ?

### ISSUE THREAD

**Issue by fipso** [ThrDev/Socks5#21]
Hey,
Just wanted to know whether i can use this lib to connect to a Socks5 Server and get a Socket.
I want to use the Socket to recive Mails via IMAP.

https://github.com/jstedfast/MailKit

Can i do that easily ? 
If yes, ist there any example ?

Thx.

**Comment by ThrDev** [comment]
Hey there fipso,

There is an easy way to get the socket directly from the SocksClient.

https://github.com/ThrDev/Socks5/blob/master/socks5/Socks5Projects/TorTestSocks/TorTestSocks/Program.cs#L25

Once you create a new instance of the SocksClient and call Connect, you should be able to access the property called "Client". This is a .NET socket.
