### ISSUE TITLE
Support UDP ?

### ISSUE THREAD

**Issue by GreatFireWall** [ThrDev/Socks5#22]

**Comment by ThrDev** [comment]
Hey @GreatFireWall,

Originally, UDP support wasn't planned for the final release, but I can look into implementing it within the next few weeks.

**Comment by Gdocal** [comment]
Hi. Are you still plan to implement UDP?

**Comment by ByronAP** [comment]
adding a +1 for reopening and adding UDP support

**Comment by GF-Huang** [comment]
> adding a +1 for reopening and adding UDP support

See this: https://github.com/GF-Huang/Socklient
