### ISSUE TITLE
memory leaks

### ISSUE THREAD

**Issue by vik78** [ThrDev/Socks5#4]
On big amount of requests there are memory leaks.
This works for me

socks5\Socks\SocksClient.cs

        void Client_onClientDisconnected(object sender, ClientEventArgs e)
        {
            this.onClientDisconnected(this, new SocksClientEventArgs(this));
            Client.onClientDisconnected -= Client_onClientDisconnected;
        }

socks5\Socks\SocksTunnel.cs

        void Client_onClientDisconnected(object sender, ClientEventArgs e)
        {
            if (disconnected) return;
            //Console.WriteLine("Client DC'd");
            disconnected = true;
            RemoteClient.Disconnect();
            RemoteClient.onDataReceived -= RemoteClient_onDataReceived;
            RemoteClient.onClientDisconnected -= RemoteClient_onClientDisconnected;
        }

        void RemoteClient_onClientDisconnected(object sender, ClientEventArgs e)
        {
            
            if (disconnected) return;
            //Console.WriteLine("Remote DC'd");
            disconnected = true;
            Client.Client.Disconnect();
            Client.Client.onDataReceived -= Client_onDataReceived;
            Client.Client.onClientDisconnected -= Client_onClientDisconnected;
        }

        SocketAsyncEventArgs _socketArgs;

        public void Open()
        {
            //....
            _socketArgs = new SocketAsyncEventArgs { RemoteEndPoint = new IPEndPoint(ModifiedReq.IP, ModifiedReq.Port) };
            _socketArgs.Completed += socketArgs_Completed;
            RemoteClient.Sock = new Socket(AddressFamily.InterNetwork, SocketType.Stream, ProtocolType.Tcp);
            if (!RemoteClient.Sock.ConnectAsync(_socketArgs))
                ConnectHandler(_socketArgs);
            }

        void socketArgs_Completed(object sender, SocketAsyncEventArgs e)
        {
        //...
            if (_socketArgs != null)
            {
                _socketArgs.Completed -= socketArgs_Completed;
                _socketArgs.Dispose();
            }
        }

**Comment by ThrDev** [comment]
This seems about right when it comes to events. Thank you for the contribution! I've updated these in the latest commit.
