### ISSUE TITLE
Can not use the compiled project in chrome, firefox, ie

### ISSUE THREAD

**Issue by jackyze** [ThrDev/Socks5#5]
I've compiled your project on 2 diffrent maschines with vista and windows 8. On both maschines i get only a file with 3 chars with trash inside my browser. Any explanation.

**Comment by ThrDev** [comment]
Could you please explain what you mean by "trash inside my browser?"
Is that when you are trying to proxy any of those browsers?

**Comment by jackyze** [comment]
I't works while using only the socks settings inside the browser and leave any other protocol empty. Before i had "Use address for all protocols". Maybe the socks catches all request for the address. But it does not really matter. Works like charm with this settings.

**Comment by ThrDev** [comment]
Let me see if I can do anything to handle that. I'll be pushing a commit tonight.
