### ISSUE TITLE
How to use encryption? 

### ISSUE THREAD

**Issue by huhu2207** [ThrDev/Socks5#6]
Hi,

Thanks for your great job!
I'm wondering how to use the encryption function in your project, can it protect the data going through the proxy? Could you please give me some examples?

Great thanks and regards,
Jackson.

**Comment by ThrDev** [comment]
The Encryption algorithm that is included with the Socks5 server is still in a beta. It's very minimal support at the moment in terms of capability and stability.
It is supported by the Socks5Client included with the Socks5 server. The data between these two will be automatically encrypted based off of the authentication method that the Socks5 server chooses.

I was actually planning on fixing the many issues it has tonight. Once I finish these issues, I will come back and post some documentation on how to utilize the Socks5 server as well as client.

**Comment by huhu2207** [comment]
Okay, thanks for you great jobs! Waiting for your good news!
