### ISSUE TITLE
sock5 can't work but Minimal OK

### ISSUE THREAD

**Issue by gitlsl** [ThrDev/Socks5#7]
i both try them, i found all of the website can be visted by SOCK5 Minimal ,but many websites can not open by SOCK5-FULL,  i use firedebug only can see  'Abort'   i think sock5 dicconnect the socket

**Comment by ThrDev** [comment]
Hello gitlsl,

How are you using the proxy? Through Internet Options? Or through a third party software like Proxifier?

**Comment by gitlsl** [comment]
@ThrDev i only run the SOCKS5 and SOCK5 Minimal test  and set SOCK5 Minimal' Authentication  to false ,    my broswer is firefox with autoproxy ,   the option of autoproxy is socks5,127.0.0.1:1080  , i  used shadow socks before which work fine all the time

**Comment by ThrDev** [comment]
I've found the issue.
https://github.com/ThrDev/Socks5/blob/master/socks5/socks5/Socks/SocksClient.cs#L69
It was finding an authentication method even if it wasn't enabled throwing the "unsupported" error.
I'll be pushing my commit soon to fix this issue.
