### ISSUE TITLE
Tor communication(Server-Client)

### ISSUE THREAD

**Issue by PanagiotisDrakatos** [ThrDev/Socks5#8]
can i have a connection to tor between (client-server) program with this library?if yes can i have an example?
I appreciate your project very nice work

**Comment by ThrDev** [comment]
Hey stathmarxis,
Yes, it is completely possible to bridge this to tor.
I will see if I can't get you an example in the next few hours.

~Thr

**Comment by ThrDev** [comment]
https://github.com/ThrDev/Socks5/tree/master/socks5/Socks5Projects/TorTestSocks

![Image of Tor]
(https://shotr.io/Gre3yKplh3.png)

I've pushed a new folder called "Socks5Projects" - this folder will now be for projects related to things of this fashion.

Anyways, the Tor bridging works perfectly and is only a few lines long.
I will leave this open for a few hours to let you respond.

Enjoy!

~ThrDev

**Comment by stathmarxis** [comment]
Maybe i didn't explain exactly what i want i want from application(server which he create .onion) the  client make connect to him through tor. If your library do something like this i will definitely donate your project i am desperate. I create a post in stackoverflow if you have time you can check it . I made this in java but i want in c# also and i cant

http://stackoverflow.com/questions/32704799/c-sharp-communication-over-tor-onion

**Comment by stathmarxis** [comment]
what other configurations do i need to run this tor client ? I run the example code and i get error can't connect to tor.I would appreciate a reply in your earliest convenience

**Comment by ThrDev** [comment]
You'll need to download the Tor client (https://www.torproject.org/dist/torbrowser/5.0.3/tor-win32-0.2.6.10.zip)
You'll also need to configure it to run on port 9050 as well as a Socks5 server with a username and a password.
